name: 'test-every-push'
on:
  push:
    branches:
      - 'master'
jobs:
  echo:
    name: 출력
    runs-on: ubuntu-latest
    steps:
      - name: 출력
        run: echo "hi"
  tag:
    name: 태그 생성
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
